### PR TITLE
fix: fix tags for shield config

### PR DESCRIPTION
**Pull request by bsushmith**
Add `mapstructure` tags to parse shield config through viper in expected ways

### CODE REVIEW

**Comment by krtkvrm** [comment]
@bsushmith can you explain the changes ?

**Comment by bsushmith** [comment]
Currently, the way the config is read and parsed is thru viper, and viper uses `mapstructure` tags and if those are not present, it uses the var names(lowercase) in the struct itself as the config key string to parse from config file. 

https://github.com/odpf/salt/blob/main/config/config.go#L174 uses mapstructure tags to get the flattened keys. At the moment, we have mapstructure tags are present for all internal fields in the shield config, but not at the top level.

example:
``` go
type DBConfig struct {
	Driver          string        `yaml:"driver" mapstructure:"driver"`
	URL             string        `yaml:"url" mapstructure:"url"`
	MaxIdleConns    int           `yaml:"max_idle_conns" mapstructure:"max_idle_conns" default:"10"`
	MaxOpenConns    int           `yaml:"max_open_conns" mapstructure:"max_open_conns" default:"10"`
	ConnMaxLifeTime time.Duration `yaml:"conn_max_life_time" mapstructure:"conn_max_life_time" default:"10ms"`
	MaxQueryTimeout time.Duration `yaml:"max_query_timeout" mapstructure:"max_query_timeout" default:"100ms"`
}
```

without these changes, the config for example `spicedb` would be expected as `spicedb.pre_shared_key` rather than `spice_db.pre_shared_key` which leads to confusion as to half of it is getting parsed using one way and other part in other way.

**Comment by rsbh** [comment]
These changes will break the current env keys, we need to update the env keys to handle this change.
viper create different keys with `yaml/json` and `mapstructure`  tags
ex. `yaml spicedb` will remove the underscore and create env `SPICEDB`
but with map structure, env keys preserve the underscore. `SPICE_DB`

**Comment by ravisuhag** [comment]
> These changes will break the current env keys, we need to update the env keys to handle this change. viper create different keys with `yaml/json` and `mapstructure` tags ex. `yaml spicedb` will remove the underscore and create env `SPICEDB` but with map structure, env keys preserve the underscore. `SPICE_DB`

I think this is configurable.

**Comment by ravisuhag** [comment]
This is already handled in a separate PR.

**Pull request closed without merging**
